<?php

use Illuminate\Database\Seeder;

class OriCompanyMetaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ori_company_meta')->delete();
        
        \DB::table('ori_company_meta')->insert(array (
            0 => 
            array (
                'id' => 1,
                'cmpny_id' => 2,
                'meta_name' => 're_open_status',
                'meta_value' => '4',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-13 17:36:52',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'cmpny_id' => 2,
                'meta_name' => 'after_re_open',
                'meta_value' => '2',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-13 17:36:52',
                'updated_at' => '2018-11-13 19:11:59',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'cmpny_id' => 2,
                'meta_name' => 'chat_agent',
                'meta_value' => '4',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-13 19:09:51',
                'updated_at' => '2019-01-11 13:03:42',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'cmpny_id' => 2,
                'meta_name' => 'esc_intimations_mail',
                'meta_value' => '17',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:49:41',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'cmpny_id' => 2,
                'meta_name' => 'esc_intimations_sms',
                'meta_value' => '18',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:49:41',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'cmpny_id' => 2,
                'meta_name' => 'esc_going_to_expire_mail',
                'meta_value' => '19',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:49:41',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'cmpny_id' => 2,
                'meta_name' => 'esc_going_to_expire_sms',
                'meta_value' => '20',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:49:41',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'cmpny_id' => 2,
                'meta_name' => 'esc_expired_mail',
                'meta_value' => '21',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:49:41',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'cmpny_id' => 2,
                'meta_name' => 'esc_expired_sms',
                'meta_value' => '22',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:49:41',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'cmpny_id' => 2,
                'meta_name' => 'esc_close_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 3,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2018-11-21 11:59:50',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'cmpny_id' => 2,
                'meta_name' => 'content_missing_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 3,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2018-11-21 11:59:50',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'cmpny_id' => 2,
                'meta_name' => 'chat_transcript_mail',
                'meta_value' => '28',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-17 18:04:04',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'cmpny_id' => 2,
                'meta_name' => 'chat_ticket_open_mail',
                'meta_value' => '9',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2018-12-03 15:46:34',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'cmpny_id' => 2,
                'meta_name' => 'chat_ticket_closed_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 3,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2018-11-21 11:59:50',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'cmpny_id' => 2,
                'meta_name' => 'feedback_mail',
                'meta_value' => '4',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-10 17:57:23',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'cmpny_id' => 2,
                'meta_name' => 'feedback_sms',
                'meta_value' => '7',
                'status' => 1,
                'created_by' => 3,
                'updated_by' => 2,
                'created_at' => '2018-11-21 11:59:50',
                'updated_at' => '2019-01-12 16:39:25',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 35,
                'cmpny_id' => 2,
                'meta_name' => 'from_name',
                'meta_value' => 'Orisys',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 36,
                'cmpny_id' => 2,
                'meta_name' => 'from_email',
                'meta_value' => 'admin@orisys.in',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 37,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_client_id',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 38,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_client_secret',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 39,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_authorized_redirect_uri',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 40,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_private_api_key',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 41,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_domain_name',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 42,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_api_key',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 43,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_host',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 44,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_encryption',
                'meta_value' => 'none',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 45,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_port',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-11-27 19:51:53',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 46,
                'cmpny_id' => 2,
                'meta_name' => 'callback',
                'meta_value' => '1form_basic_reload',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-27 19:51:53',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 47,
                'cmpny_id' => 2,
                'meta_name' => 'open_status',
                'meta_value' => '1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-28 10:01:15',
                'updated_at' => '2018-12-03 11:25:54',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 48,
                'cmpny_id' => 2,
                'meta_name' => 'set_crm_source',
                'meta_value' => '4',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-28 10:01:15',
                'updated_at' => '2019-01-23 11:16:36',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 49,
                'cmpny_id' => 2,
                'meta_name' => 'set_crm_automation_source',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-28 10:01:15',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 50,
                'cmpny_id' => 2,
                'meta_name' => 'sales_automation_lead_stage',
                'meta_value' => '1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-28 10:01:15',
                'updated_at' => '2019-01-12 12:43:34',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 51,
                'cmpny_id' => 2,
                'meta_name' => 'auto_stage_activation',
                'meta_value' => '1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-28 10:01:15',
                'updated_at' => '2019-01-12 12:43:34',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 52,
                'cmpny_id' => 2,
                'meta_name' => 'set_manual_call_query_type',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-28 10:01:15',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 53,
                'cmpny_id' => 2,
                'meta_name' => 'agent',
                'meta_value' => '3',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-30 13:03:17',
                'updated_at' => '2018-12-17 11:22:15',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 54,
                'cmpny_id' => 2,
                'meta_name' => 'auto_mail_response',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-11-30 13:03:17',
                'updated_at' => '2018-11-30 13:03:17',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 55,
                'cmpny_id' => 2,
                'meta_name' => 'chat_ticket',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-03 15:52:31',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 56,
                'cmpny_id' => 2,
                'meta_name' => 'sales_automation_failure_mailid',
                'meta_value' => 'rinku.eb@orisys.in',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-03 15:52:31',
                'updated_at' => '2019-01-12 12:43:34',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 112,
                'cmpny_id' => 2,
                'meta_name' => 'lead_src_type_chat',
                'meta_value' => '8',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-07 12:22:17',
                'updated_at' => '2018-12-07 12:22:17',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 149,
                'cmpny_id' => 2,
                'meta_name' => 'te',
                'meta_value' => 'sendgrid_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-11 16:15:25',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 150,
                'cmpny_id' => 2,
                'meta_name' => 'ts',
                'meta_value' => 'valuefirst_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-15 12:46:24',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 151,
                'cmpny_id' => 2,
                'meta_name' => 'elitbuzz_sender_id_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-15 12:46:24',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 152,
                'cmpny_id' => 2,
                'meta_name' => 'elitbuzz_user_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 153,
                'cmpny_id' => 2,
                'meta_name' => 'elitbuzz_password_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 154,
                'cmpny_id' => 2,
                'meta_name' => 'valuefirst_user_name_1',
                'meta_value' => 'demohypersoft',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-18 10:16:04',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 155,
                'cmpny_id' => 2,
                'meta_name' => 'valuefirst_password_1',
                'meta_value' => 'demohy11',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-18 10:16:04',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 156,
                'cmpny_id' => 2,
                'meta_name' => 'valuefirst_from_name_1',
                'meta_value' => 'ORICOM',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-18 10:16:04',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 157,
                'cmpny_id' => 2,
                'meta_name' => 'valuefirst_url_1',
                'meta_value' => 'http://203.212.70.200/smpp/sendsms?',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 158,
                'cmpny_id' => 2,
                'meta_name' => 'valuefirst_responcefull_url_1',
                'meta_value' => '&udh=&dlr-mask=19&dlr-url=http://206.189.135.49/save_sms_response?myid=%255%26status=%25d%26reciever=%25p%26updated_on=%25t%26res=%252',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:56:10',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 159,
                'cmpny_id' => 2,
                'meta_name' => 'transcation_sms',
                'meta_value' => 'valuefirst_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 160,
                'cmpny_id' => 2,
                'meta_name' => 'esms_sender_id_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 161,
                'cmpny_id' => 2,
                'meta_name' => 'esms_user_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 162,
                'cmpny_id' => 2,
                'meta_name' => 'esms_password_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 163,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_host_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 164,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_encryption_1',
                'meta_value' => 'none',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 165,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_port_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 166,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_user_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 167,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_password_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 168,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_from_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 169,
                'cmpny_id' => 2,
                'meta_name' => 'gmail_from_email_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 170,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_host_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 171,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_encryption_1',
                'meta_value' => 'none',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 172,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_port_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 173,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_user_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 174,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_password_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 175,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_from_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 176,
                'cmpny_id' => 2,
                'meta_name' => 'mailgun_from_email_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 177,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_host_1',
                'meta_value' => 'smtp.sendgrid.net',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:57:19',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 178,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_encryption_1',
                'meta_value' => 'ssl',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:57:19',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 179,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_port_1',
                'meta_value' => '587',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:57:19',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 180,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_user_name_1',
                'meta_value' => 'oricoms',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-22 21:35:02',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 181,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_password_1',
                'meta_value' => 'orisys@1a',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-22 21:35:02',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 182,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_from_name_1',
                'meta_value' => 'GCC',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-22 15:28:01',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 183,
                'cmpny_id' => 2,
                'meta_name' => 'sendgrid_from_email_1',
                'meta_value' => 'oricomscrm@gmail.com',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2019-01-22 22:10:40',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 184,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_host_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 185,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_encryption_1',
                'meta_value' => 'none',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 186,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_port_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 187,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_user_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 188,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_password_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 189,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_from_name_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 190,
                'cmpny_id' => 2,
                'meta_name' => 'smtp_from_email_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-13 18:55:49',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 191,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_host_1',
                'meta_value' => 'smtp.sendgrid.net',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 192,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_encryption_1',
                'meta_value' => 'ssl',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 193,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_port_1',
                'meta_value' => '587',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 194,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_user_name_1',
                'meta_value' => 'chinnu.l@orisys.in',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 195,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_password_1',
                'meta_value' => 'Mypassword#1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 196,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_from_name_1',
                'meta_value' => 'Chinnu',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 197,
                'cmpny_id' => 2,
                'meta_name' => 'mailchimp_from_email_1',
                'meta_value' => 'chinnu.l@orisys.in',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:55:49',
                'updated_at' => '2018-12-17 16:02:22',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 198,
                'cmpny_id' => 2,
                'meta_name' => 'transcation_email',
                'meta_value' => 'sendgrid_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-13 18:56:21',
                'updated_at' => '2018-12-17 16:04:31',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 199,
                'cmpny_id' => 2,
                'meta_name' => 'mail_server_host_1',
                'meta_value' => 'imap.gmail.com:993/imap/ssl',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-17 11:15:09',
                'updated_at' => '2019-02-07 13:08:04',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 200,
                'cmpny_id' => 2,
                'meta_name' => 'mail_server_username_1',
                'meta_value' => 'oriesmarti@gmail.com',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-17 11:15:09',
                'updated_at' => '2019-01-17 10:15:00',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 201,
                'cmpny_id' => 2,
                'meta_name' => 'mail_server_password_1',
                'meta_value' => 'orisystest',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-17 11:15:09',
                'updated_at' => '2019-01-17 10:15:00',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 202,
                'cmpny_id' => 2,
                'meta_name' => 'push_key',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2018-12-17 11:15:09',
                'updated_at' => '2018-12-17 11:15:09',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 203,
                'cmpny_id' => 2,
                'meta_name' => 'set_unattended_call_source',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-02 16:33:17',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 204,
                'cmpny_id' => 2,
                'meta_name' => 'set_abandoned_category',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-02 16:33:17',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 205,
                'cmpny_id' => 2,
                'meta_name' => 'set_after_hour_category',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-02 16:33:17',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 206,
                'cmpny_id' => 2,
                'meta_name' => 'set_holiday_category',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-02 16:33:17',
                'updated_at' => '2019-02-07 13:07:06',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 207,
                'cmpny_id' => 2,
                'meta_name' => 'promotion_email',
                'meta_value' => 'sendgrid_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-11 15:36:32',
                'updated_at' => '2019-01-11 15:36:32',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 208,
                'cmpny_id' => 2,
                'meta_name' => 'notification_email',
                'meta_value' => 'sendgrid_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-11 15:36:32',
                'updated_at' => '2019-01-11 15:36:32',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 209,
                'cmpny_id' => 2,
                'meta_name' => 'promotion_sms',
                'meta_value' => 'valuefirst_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-11 16:15:25',
                'updated_at' => '2019-01-11 16:15:25',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 210,
                'cmpny_id' => 2,
                'meta_name' => 'notification_sms',
                'meta_value' => 'valuefirst_1',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-11 16:15:25',
                'updated_at' => '2019-01-15 12:45:47',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 211,
                'cmpny_id' => 2,
                'meta_name' => 'outbound_caller_id',
                'meta_value' => '4712737870',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-11 16:40:33',
                'updated_at' => '2019-01-22 18:40:00',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 215,
                'cmpny_id' => 1,
                'meta_name' => 'open_status',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 216,
                'cmpny_id' => 1,
                'meta_name' => 're_open_status',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 217,
                'cmpny_id' => 1,
                'meta_name' => 'after_re_open',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 218,
                'cmpny_id' => 1,
                'meta_name' => 'chat_ticket',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 219,
                'cmpny_id' => 1,
                'meta_name' => 'chat_agent',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 220,
                'cmpny_id' => 1,
                'meta_name' => 'agent',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 221,
                'cmpny_id' => 1,
                'meta_name' => 'set_crm_source',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 222,
                'cmpny_id' => 1,
                'meta_name' => 'set_crm_automation_source',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 223,
                'cmpny_id' => 1,
                'meta_name' => 'set_unattended_call_source',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 224,
                'cmpny_id' => 1,
                'meta_name' => 'sales_automation_lead_stage',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 225,
                'cmpny_id' => 1,
                'meta_name' => 'auto_stage_activation',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 226,
                'cmpny_id' => 1,
                'meta_name' => 'sales_automation_failure_mailid',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 227,
                'cmpny_id' => 1,
                'meta_name' => 'mail_server_host_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-02-07 13:09:02',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 228,
                'cmpny_id' => 1,
                'meta_name' => 'mail_server_username_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 229,
                'cmpny_id' => 1,
                'meta_name' => 'mail_server_password_1',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 230,
                'cmpny_id' => 1,
                'meta_name' => 'push_key',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 231,
                'cmpny_id' => 1,
                'meta_name' => 'esc_intimations_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 232,
                'cmpny_id' => 1,
                'meta_name' => 'esc_intimations_sms',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 233,
                'cmpny_id' => 1,
                'meta_name' => 'esc_going_to_expire_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 234,
                'cmpny_id' => 1,
                'meta_name' => 'esc_going_to_expire_sms',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 235,
                'cmpny_id' => 1,
                'meta_name' => 'esc_expired_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 236,
                'cmpny_id' => 1,
                'meta_name' => 'lead_src_type_chat',
                'meta_value' => '4',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 237,
                'cmpny_id' => 1,
                'meta_name' => 'outbound_caller_id',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 238,
                'cmpny_id' => 1,
                'meta_name' => 'esc_expired_sms',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 239,
                'cmpny_id' => 1,
                'meta_name' => 'esc_close_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 240,
                'cmpny_id' => 1,
                'meta_name' => 'content_missing_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 241,
                'cmpny_id' => 1,
                'meta_name' => 'auto_mail_response',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 242,
                'cmpny_id' => 1,
                'meta_name' => 'chat_transcript_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 243,
                'cmpny_id' => 1,
                'meta_name' => 'chat_ticket_open_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 244,
                'cmpny_id' => 1,
                'meta_name' => 'chat_ticket_closed_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 245,
                'cmpny_id' => 1,
                'meta_name' => 'feedback_mail',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 246,
                'cmpny_id' => 1,
                'meta_name' => 'feedback_sms',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 247,
                'cmpny_id' => 1,
                'meta_name' => 'set_manual_call_query_type',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 248,
                'cmpny_id' => 1,
                'meta_name' => 'set_abandoned_category',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 249,
                'cmpny_id' => 1,
                'meta_name' => 'set_after_hour_category',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 250,
                'cmpny_id' => 1,
                'meta_name' => 'set_holiday_category',
                'meta_value' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-01-14 12:25:12',
                'updated_at' => '2019-01-14 12:25:12',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 251,
                'cmpny_id' => 2,
                'meta_name' => 'enquiry_email',
                'meta_value' => '33',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-22 11:04:55',
                'updated_at' => '2019-01-22 11:04:55',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 252,
                'cmpny_id' => 2,
                'meta_name' => 'enquiry_sms',
                'meta_value' => '35',
                'status' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2019-01-22 11:04:55',
                'updated_at' => '2019-01-22 11:04:55',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}